import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "./style/globals.css";
import 'react-toastify/dist/ReactToastify.css';
import Sidebar from "./pages/Sidebar";
import Header from "./components/Header";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ inter.className }>
        <Header />
        { children }
        <Sidebar />
        <Footer />
        <ToastContainer
          position="top-left"
          autoClose={ 2000 }
          theme='light'
        />
      </body>
    </html>
  );
}
